theme = "onedark"
icons = "awesome"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_used_percents}"
format_swap = "{swap_used_percents}"

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "net"
icons_format = " {icon}  "
format = "{ssid} {ip}"
interval = 5

[[block]]
block = "backlight"

[[block]]
block = "time"
interval = 5
format = "%a %d/%m %R"

[[block]]
block = "battery"
if_command = "test -e /sys/class/power_supply/BAT0"
device = "/sys/class/power_supply/BAT0"
icons_format = " {icon}  "
format = "{time} {percentage}"
full_format = "{time} {percentage}"

[[block]]
block = "battery"
if_command = "test -e /sys/class/power_supply/BAT1"
device = "/sys/class/power_supply/BAT1"
icons_format = "{icon}  "
format = "{time} {percentage}"
full_format = "{percentage}"

[[block]]
block = "custom"
