[theme]
theme = "onedark"
[icons]
icons = "awesome"

[[block]]
block = "cpu"
interval = 1
format = " $utilization.eng() $frequency.eng()"
format_alt = "$utilization.eng() $frequency.eng() $barchart.str()"

[[block]]
block = "memory"
format = "$mem_used_percents.eng(2)"
interval = 1
warning_mem = 70
critical_mem = 90

[[block]]
block = "disk_space"
info_type = "available"
alert_unit = "GB"
format = "$available.eng(2)"

[[block]]
block = "net"
format = " {$signal_strength $ssid $frequency|Wired} $device"

[[block]]
if_command = "test -e /sys/class/backlight/intel_backlight/brightness"
block = "backlight"
device = "intel_backlight"

[[block]]
block = "time"
interval = 5
format = "%a %d/%m %R"

[[block]]
block = "battery"
if_command = "test -e /sys/class/power_supply/BAT0"
device = "BAT0"
format = " $time $percentage $power"
full_format = " $percentage"
empty_format = " "

[[block]]
block = "battery"
if_command = "test -e /sys/class/power_supply/BAT1"
device = "BAT1"
format = " $time $percentage $power"
full_format = " $percentage"
empty_format = " "
